### ISSUE TITLE
"ImageJ with Python Kernel" section 6.2 doesn't work

### ISSUE THREAD

**Issue by ChasNelson1990** [imagej/tutorials#78] opened 2019-11-19 16:40 UTC
I'm not convinced section 6.2 (Example: Run a plugin: ij.py.run_plugin) of the "ImageJ with Python Kernel" is actually working.

If you look at the two plots of 'blobs' and 'results' [in the binder version], they appear to be identical. Definitely not blurred.

In fact, I'm running an almost identical version of this code locally and no matter what I try I don't seem to be able to get the result from Mean back into Python.

**Comment by ChasNelson1990** [comment] 2019-11-19 16:45
I've also raised this with the pyimagej repo: https://github.com/imagej/pyimagej/issues/51

**Comment by ctrueden** [comment] 2019-12-10 13:54
Sorry for the delay in reply, @ChasNelson1990!

The problem is caused by imagej/pyimagej#36, because the "Mean" plugin that the notebook executes there is not a built-in ImageJ1 plugin, but rather something included with Fiji: `mpicbg.ij.plugin.Mean`. And those extra plugins were only working when wrapping a local Fiji installation, not when launching a Fiji using the `imagej.init('sc.fiji:fiji')` syntax.

Fortunately, with the merge of imagej/imagej-legacy#228, this problem is fixed. The fix will be included in a new Fiji release soon, but in the meantime, you can avoid the issue by changing the top of the notebook to include the updated imagej-legacy library, as follows:
```python
ij = imagej.init('sc.fiji:fiji:2.0.0-pre-10+net.imagej:imagej-legacy:0.37.0')
```

**Closed by ctrueden** 2019-12-10 13:54 UTC
