### ISSUE TITLE
initialization error

### ISSUE THREAD

**Issue by tischi** [imagej/tutorials#36] opened 2017-03-05 09:31 UTC
I tried to run the Beaker demo, but for me it says: "Initialization failed". 
If I then anyway try to run the first cell, where ImageJ is loaded, I get these error messages: 

`General error during conversion: Error grabbing Grapes -- [download failed: org.ow2.asm#asm;5.0.4!asm.jar, download failed: org.ow2.asm#asm-util;5.0.4!asm-util.jar, download failed: org.ow2.asm#asm-tree;5.0.4!asm-tree.jar, download failed: org.ow2.asm#asm-commons;5.0.4!asm-commons.jar]`

I am using a Mac in case that could be part of the problem?!

**Comment by haesleinhuepf** [comment] 2017-03-08 10:57
I do have the same issue on my Mac and on my Windows10 laptop as well. Furthermore, I traced down if these dependencies exist. Apparently they do: 
http://maven.imagej.net/content/groups/public/org/ow2/asm/asm/5.0.4/
http://maven.imagej.net/content/groups/public/org/ow2/asm/asm-util/5.0.4/
http://maven.imagej.net/content/groups/public/org/ow2/asm/asm-tree/5.0.4/
http://maven.imagej.net/content/groups/public/org/ow2/asm/asm-commons/5.0.4/

I'm new to this groovy/gradle caching thingy. Could it be that the files in the maven repo are corrupted? Could it help to enter another repo to download the files from there?

**Comment by imagejan** [comment] 2017-03-08 11:56
I got a similar error when first trying out the notebooks:
https://gitter.im/imagej/imagej?at=589378584c04e9a44e61f4dd

But manually copying the `asm-tree` as suggested by @ctrueden solved it for me:
```
cp ~/.m2/repository/org/ow2/asm/asm-tree/5.0.4/asm-tree-5.0.4.jar ~/.groovy/grapes/org.ow2.asm/asm-tree/jars/asm-tree-5.0.4.jar
```

At that time I also had problems with the firewall and had to set the proxy configuration:
https://github.com/imagej/tutorials/commit/211e9a04659019bea7477233151b3e648741fd63

I'm still unsure what is causing this in the first place...

**Comment by ctrueden** [comment] 2017-03-14 18:53
Yes, it seems that several people are getting stuck on that asm dependency. It is coming in via jruby, and I doubt you will actually need to do something requiring it in the notebook. So you can try:

```
@Grab('net.imagej:imagej:2.0.0-rc-59')
@GrabExclude('org.scijava:scripting-jruby')
```

Could someone affected please try that, and see if it prevents the error?

**Comment by tischi** [comment] 2017-03-15 08:30
I tested it with my Mac and the following works:
```
@GrabExclude('org.scijava:scripting-renjin')
@GrabResolver(name='imagej', root='http://maven.imagej.net/content/groups/public/')
@Grab('net.imagej:imagej:2.0.0-rc-59')
```
For me, excluding the jruby was **not** necessary
```
@GrabExclude('org.scijava:scripting-jruby')
```

**Comment by ctrueden** [comment] 2017-03-15 16:21
@tischi Did you take care to test each time with a clean `~/.groovy/grapes`? Otherwise, subsequent tests are corrupted by the results of previous attempts.

**Comment by haesleinhuepf** [comment] 2017-03-16 08:07
I can confirm, it works on MacOS. I also just exclude did the following after deleting `~/.groovy/grapes`. I'll test Windows as well back home

```
@GrabExclude('org.scijava:scripting-renjin')
@GrabResolver(name='imagej', root='http://maven.imagej.net/content/groups/public/')
@Grab('net.imagej:imagej:2.0.0-rc-59')
```

Thanks @ctrueden ! Anywhere-running ImageJ-Beaker-notebooks are an awesome step ahead!

**Comment by ctrueden** [comment] 2017-03-20 20:59
Thanks for the confirmation, @haesleinhuepf.

So here is a question for the community: which scripting languages do you feel should be part of _core ImageJ_—i.e., come automatically when you depend on `net.imagej:imagej`?

It seems to me that Renjin could be put onto its own "R" update site, thus avoiding this specific problem. What about others? We could of course put every language onto its own update site, but would this make you unhappy as a developer when you depend on `net.imagej:imagej` and those languages are not available?

**Comment by ctrueden** [comment] 2017-11-30 16:49
I am closing this issue, since the scijava-jupyter-kernel is our current approach, and does not suffer from the grape grabbing weirdness. However, we do have scijava-grab to extend which libraries are available at runtime. And I actually want to transition the SJJK to be as minimal as possible, in favor of all dependencies being explicitly declared via the `#@dependency` mechanism. So this problem _might_ return. If/when that happens, we can reopen.

**Closed by ctrueden** 2017-11-30 16:49 UTC
